version: "3.1"

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_USER: gengsu07
      MB_DB_PASS: Gengsu!sh3r3
      MB_DB_HOST: postgres
    networks:
      - dbstack_default

  postgres-metabase:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gengsu07
      POSTGRES_PASSWORD: Gengsu!sh3r3
      POSTGRES_DB: metabase
    networks:
      - dbstack_default

networks:
  dbstack_default:
    external:
      name: dbstack_default
